### ISSUE TITLE
Error when getting visible region from controller

### ISSUE THREAD

**Issue by noorbakerally** [m0nac0/flutter-mapbox-gl#234]
I am getting the following error when executing the line `LatLngBounds latLngBounds = await maplibreMapController.getVisibleRegion();`

```
southwest.latitude <= northeast.latitude

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new LatLngBounds (package:maplibre_gl_platform_interface/src/location.dart:73:16)
#3      MethodChannelMaplibreGl.getVisibleRegion (package:maplibre_gl_platform_interface/src/method_channel_mapbox_gl.dart:346:14)
<asynchronous suspension>
#4      Navigation.turnNavOff (package:app/app/pages/Map/MapLibreWidget/Extensions/Navigation/RouteNavigation.dart:200:33)
<asynchronous suspension>

```

**Comment by m0nac0** [comment]
@noorbakerally Are you still seeing this issue?
If yes, what region of the earth is visible when you get that error? I assume it may be related to the meridian / antimeridian

**Comment by gabbopalma** [comment]
We apologize for responding to this issue after such a long time. It has been resolved over time.
