### ISSUE TITLE
Layer already exists

### ISSUE THREAD

**Issue by sqcsabbey** [m0nac0/flutter-mapbox-gl#237]
I'm getting this stack trace, any advice on how to avoid it? I'm using the map style from https://api.maptiler.com/maps/hybrid/style.json, but I don't believe I've made any attempts at interacting with symbols before this happens...

```
W/Mbgl    (30998): {GLThread 36570}[ParseStyle]: Layer 'KOZd2B0cOE_0' has an invalid value for text-font and will not render text. Output values must be contained as literals within the expression.
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): Failed to handle method call
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer KOZd2B0cOE_0 already exists
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.mapbox.mapboxsdk.maps.NativeMapView.addLayer(NativeMapView.java:832)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.mapbox.mapboxsdk.maps.Style.addLayer(Style.java:190)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.mapbox.mapboxgl.MapboxMapController.addSymbolLayer(MapboxMapController.java:424)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.mapbox.mapboxgl.MapboxMapController.onMethodCall(MapboxMapController.java:902)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at android.os.Looper.loop(Looper.java:250)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at android.app.ActivityThread.main(ActivityThread.java:7868)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#plugins.flutter.io/mapbox_maps_0(30998): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by sqcsabbey** [comment]
When a style loads, I was calling:
```    
    _maplibreController.setSymbolIconAllowOverlap(true);
    _maplibreController.setSymbolIconIgnorePlacement(true);
```

... that was rebuilding the symbol layer twice (once for each of these calls), and it looks like there's a timing issue there; `await`ing these calls fixed this for me.
