### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected 

### ISSUE THREAD

**Issue by harsh24** [m0nac0/flutter-mapbox-gl#272]
Exception in onDidFinishLoadingStyle
                                                                                                    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~HdSzGVrr1JXGOHvzx-QdsQ==/com.wildvisa.olt2-raXiOeUm50xaEcJFIHhaBA==/base.apk!classes6.dex)
                                                                                                    	at com.mapbox.mapboxsdk.location.engine.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:59)
                                                                                                    	at com.mapbox.mapboxsdk.location.engine.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:27)
                                                                                                    	at com.mapbox.mapboxsdk.location.engine.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:35)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1265)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1393)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:517)
                                                                                                    	at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:292)
                                                                                                    	at com.mapbox.mapboxgl.MapboxMapController.updateMyLocationEnabled(MapboxMapController.java:1788)
                                                                                                    	at com.mapbox.mapboxgl.MapboxMapController.access$100(MapboxMapController.java:101)
                                                                                                    	at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:157)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:962)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:224)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1346)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
                                                                                                    	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1119)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:186)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by kuhnroyal** [comment]
Duplicate of https://github.com/maplibre/flutter-maplibre-gl/issues/202 I think

**Comment by harsh24** [comment]
fixed by #270
