### ISSUE TITLE
`addLine` results in Null check operator used on a null value

### ISSUE THREAD

**Issue by Matix-Media** [m0nac0/flutter-mapbox-gl#358]
I am currently trying to add lines to my map, but whenever I try that I get following error in my console:
```
E/flutter ( 9956): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 9956): #0      MaplibreMapController.addLine (package:maplibre_gl/src/controller.dart:805:22)
E/flutter ( 9956): #1      _ActiveRideCardState.build.<anonymous closure>.<anonymous closure> (package:fahrtenbuch_flutter/widgets/active_ride_card.dart:64:42)
E/flutter ( 9956): #2      _MaplibreMapState.onPlatformViewCreated (package:maplibre_gl/src/maplibre_map.dart:335:27)
E/flutter ( 9956): <asynchronous suspension>
```

This is the code for adding a new line;
```dart
                    onMapCreated: (controller) async {
                      OwnActiveRide activeRide = ridesStore.activeRide as OwnActiveRide;
                      LatLng? lastCheckpoint;
                      
                      for (LatLng checkpoint in activeRide.checkpoints) {
                        if (lastCheckpoint == null) {
                          lastCheckpoint = checkpoint;
                          continue;
                        }

                        print("Adding line from ${lastCheckpoint.toString()} to ${checkpoint.toString()}");
                        await controller.addLine(LineOptions(
                          draggable: false,
                          lineColor: "#ffffff",
                          lineWidth: 15,
                          geometry: [
                            lastCheckpoint,
                            checkpoint
                          ]
                        ));

                        lastCheckpoint = checkpoint;
                      }

```

**Comment by kgilbert-act** [comment]
I'm getting the same result when using the addSymbol function

**Comment by Kyleg97** [comment]
Getting the same result when using the addSymbol function.

**Comment by m0nac0** [comment]
Does this happen before or after the `onStyleLoadedCallback` has fired?

**Comment by Matix-Media** [comment]
Okay, so I moved the line code into `onStyleLoadedCallback`. And now it works. It is weird to setup though, since I have to export the controller out of the `onMapCreated` (callback) to use it in the `onStyleLoadedCallback`.

Edit: Nvm, I can just attach the callback to the controller directly.

**Comment by ishafiul** [comment]
facing the same problem. any solution?

**Comment by ishafiul** [comment]
also, I'm facing some issues when trying to use GeoJson

```
Abort message: 'JNI DETECTED ERROR IN APPLICATION: can't call java.lang.Object[] java.util.List.toArray() on null object
    in call to CallObjectMethodV'
```
here is my code
``` dart
final List<List<double>> coordinates = [
    [-122.48369693756104, 37.83381888486939],
    [-122.48348236083984, 37.83317489144141],
    [-122.48339653015138, 37.83270036637107],
    [-122.48356819152832, 37.832056363179625],
    [-122.48404026031496, 37.83114119107971],
    [-122.48404026031496, 37.83049717427869],
    [-122.48348236083984, 37.829920943955045],
    [-122.48356819152832, 37.82954808664175],
    [-122.48507022857666, 37.82944639795659],
    [-122.48610019683838, 37.82880236636284],
    [-122.48695850372314, 37.82931081282506],
    [-122.48700141906738, 37.83080223556934],
    [-122.48751640319824, 37.83168351665737],
    [-122.48803138732912, 37.832158048267786],
    [-122.48888969421387, 37.83297152392784],
    [-122.48987674713133, 37.83263257682617],
    [-122.49043464660643, 37.832937629287755],
    [-122.49125003814696, 37.832429207817725],
    [-122.49163627624512, 37.832564787218985],
    [-122.49223709106445, 37.83337825839438],
    [-122.49378204345702, 37.83368330777276],
  ];

  try {
    await controller.removeLayer('route');
    await controller.removeSource('route');
  } catch (e) {
   
  }

 
  await controller.addSource(
    'route',
    GeojsonSourceProperties(
      data: {
        'type': 'Feature',
        'geometry': {
          'type': 'LineString',
          'coordinates': coordinates,
        },
        'properties': {},
      },
    ),
  );

 
  await controller.addLayer(
    'route',
    'route',
    const LineLayerProperties(
      lineColor: '#888', 
      lineWidth: 8.0,     
      lineJoin: 'round',  
      lineCap: 'round',   
    ),

  );

```

**Comment by gabbopalma** [comment]
Closing as resolved in the latest versions.
