### ISSUE TITLE
Doesn't seem to work on Web

### ISSUE THREAD

**Issue by MehmetMcfly** [m0nac0/flutter-mapbox-gl#62]
I am using Flutter Web to create a PWA.

I'm stuck at making MaplilbreMap work.
The following is the code I am trying to use, where I use a real URL or a style Json in place of `"...myStyleURL"`.

Is there a minimal working example for MapboxMap that works on Web Apps?

```
MaplibreMap(
          cameraTargetBounds: _getCameraTargetBounds(),
          compassViewPosition: CompassViewPosition.TopRight,
          zoomGesturesEnabled: true,
          onCameraTrackingChanged: (v) {
            print(v);
          },
          myLocationRenderMode: MyLocationRenderMode.COMPASS,
          onMapCreated: _onMapCreated,
          onMapClick: widget.onMapClick != null ? (_, __) => widget.onMapClick!() : null,
          onStyleLoadedCallback: () async {//doing stuff
          },
          myLocationEnabled: true,
          styleString: "...myStyleURL",
          initialCameraPosition: _getCameraPosition(),
        ),
```

The error I get is the following:
```
Height of Platform View type: [plugins.flutter.io/mapbox_gl_271250816] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [plugins.flutter.io/mapbox_gl_271250816] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
TypeError: Cannot read properties of undefined (reading 'LngLat')
    at Function.new (http://localhost:53323/packages/mapbox_gl_dart/src/util/evented.dart.lib.js:4206:71)
    at mapbox_gl_web.MaplibreMapController.new.initPlatform (http://localhost:53323/packages/maplibre_gl_web/mapbox_gl_web.dart.lib.js:1068:170)
    at initPlatform.next (<anonymous>)
    at http://localhost:53323/dart_sdk.js:42610:33
    at _RootZone.runUnary (http://localhost:53323/dart_sdk.js:42466:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53323/dart_sdk.js:37033:29)
    at handleValueCallback (http://localhost:53323/dart_sdk.js:37636:49)
    at Function._propagateToListeners (http://localhost:53323/dart_sdk.js:37674:17)
    at _Future.new.[_complete] (http://localhost:53323/dart_sdk.js:37508:25)
    at Object._cancelAndValue (http://localhost:53323/dart_sdk.js:42920:24)
    at http://localhost:53323/dart_sdk.js:21910:17
    at Object._checkAndCall (http://localhost:53323/dart_sdk.js:5598:16)
    at Object.dcall (http://localhost:53323/dart_sdk.js:5603:17)
    at HTMLLinkElement.<anonymous> (http://localhost:53323/dart_sdk.js:115371:23)
```

**Comment by MehmetMcfly** [comment]
Looks like I needed some information in my Index.html.
